[package]
name = "sena"
version = "0.1.0"
edition = "2021"

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dependencies]
either = { version = "1.11.0", default-features = false }
tokio = { version = "1.37.0", features = ["sync"], optional = true }
